name: grmpy_tutorial

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - sphinxcontrib.bibtex
  - sphinx_rtd_theme
  - linearmodels
  - json
  - matplotlib
  - seaborn

